DROP DATABASE IF EXISTS delphos;
CREATE DATABASE delphos;
USE delphos;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";

CREATE TABLE `usuarios`(
    `ID` INTEGER AUTO_INCREMENT,
    `NOMBRE` VARCHAR(20) NOT NULL,
    `PASSWORD` VARCHAR(10) NOT NULL,
    `TELEFONO` VARCHAR(15) NOT NULL,
    `DIRECCION` VARCHAR(50) NOT NULL,
    `EDAD` INTEGER NOT NULL,
    PRIMARY KEY(`ID`)
) ENGINE = InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `curso`(
    `IDCURSO` INTEGER AUTO_INCREMENT,
    `CODIGO` VARCHAR(50) NOT NULL,
    `NOMBRE` VARCHAR(100) NOT NULL,
    PRIMARY KEY(`IDCURSO`)
)ENGINE = InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `alumno`(
    `ID` INTEGER,
    `IDCURSO` INTEGER,
    CONSTRAINT FK_ALU_ID FOREIGN KEY (ID) REFERENCES usuarios(ID),
    CONSTRAINT FK_ALU_CUR FOREIGN KEY (IDCURSO) REFERENCES curso(IDCURSO)
) ENGINE = InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `rol`(
    `ID` INTEGER,
    `DESCRPICION` VARCHAR(15) NOT NULL,
    PRIMARY KEY(`ID`)
) ENGINE = InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `roles_asignados`(
    `ID` INTEGER AUTO_INCREMENT,
    `ID_ROL` INTEGER NOT NULL,
    `ID_USUARIO` INTEGER NOT NULL,
    CONSTRAINT FK_ROL_TIP FOREIGN KEY(ID_ROL) REFERENCES rol(ID),
    CONSTRAINT FK_USU_ROL FOREIGN KEY(ID_USUARIO) REFERENCES usuarios(ID),
    PRIMARY KEY(`ID`)
)ENGINE = InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `imparte`(
    `ID` INTEGER AUTO_INCREMENT,
    `COD_PROFESOR` INTEGER NOT NULL,
   	`COD_CURSO` INTEGER NOT NULL,
    CONSTRAINT FK_IMP_PRO FOREIGN KEY (COD_PROFESOR) REFERENCES usuarios(ID),
    CONSTRAINT FK_IMP_CUR FOREIGN KEY (COD_CURSO) REFERENCES curso(IDCURSO),
    PRIMARY KEY(`ID`)
)ENGINE = InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `notas`(
    `ID` INTEGER AUTO_INCREMENT,
    `COD_ALUMNO` INTEGER NOT NULL,
    `COD_PROFESOR` INTEGER NOT NULL,
    `NOTA` FLOAT NOT NULL,
    CONSTRAINT FK_NOT_PRO FOREIGN KEY (COD_PROFESOR) REFERENCES usuarios(ID),
    CONSTRAINT FK_NOT_ALU FOREIGN KEY (COD_ALUMNO) REFERENCES usuarios (ID),
    PRIMARY KEY(`ID`)
)ENGINE = InnoDB DEFAULT CHARSET=latin1;
   
COMMIT;